- type: clock
  hour-format: 24h
  timezones:
    - timezone: Europe/Paris
      label: Paris
    - timezone: Asia/Tokyo
      label: Tokyo
- type: weather
  location: Quatre Bornes, Mauritius
  units: metric # alternatively "imperial"
  hour-format: 24h # alternatively "12h"
  # Optionally hide the location from being displayed in the widget
  # hide-location: true
- type: calendar
  first-day-of-week: monday

#Listing my own github repos
- type: custom-api
  title: GitHub Repositories
  url: https://api.github.com/user/repos
  cache: 1d
  parameters:
    affiliation: owner
    sort: updated
    visibility: all
  headers:
    Authorization: Bearer ${GITHUB_PERSONAL_API_TOKEN}
    Accept: application/vnd.github.v3+json
    User-Agent: Glance-Dashboard
  template: |
    <div class="github-repos">
      <ul class="list list-gap-14 collapsible-container" data-collapse-after="5">
        {{ range .JSON.Array "" }}
          <li>
            <a class="size-h3 color-primary" href="{{ .String "html_url" }}">{{ .String "full_name" }}</a>
            <h3><a href="" target="_blank"></a></h3>
            <p>{{ .String "description" }}</p>
            <ul class="list-horizontal-text device-info">
              <li data-popover-type="html"><div data-popover-html="">Last Update</div>{{ formatTime "DateOnly" ( parseTime "RFC3339" (.String "updated_at") ) }}</li>
              <li data-popover-type="html"><div data-popover-html="">Visibility</div>{{ .String "visibility" }}</li>
              <li data-popover-type="html"><div data-popover-html="">Stars</div>{{ .Int "stargazers_count" }}✩</li>
              {{ if .String "language" }}
              <li data-popover-type="html"><div data-popover-html="">Language</div>{{ .String "language" }}</li>
              {{ end }}     
            </ul>
          </li>
        {{ end }}
      </ul>
    </div>

- type: to-do

#SPEEDTEST API
- $include: speedtest-widget.yml