- name: Main
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  hide-desktop-navigation: true
  center-vertically: true
  width: wide

  # SEARCH BAR
  head-widgets:
      - type: search
        hide-header: true
        search-engine: duckduckgo
        bangs:
          - title: YouTube
            shortcut: "!yt"
            url: https://www.youtube.com/results?search_query={QUERY}

  columns:
    # LEFT SIDE BAR (GETS HIDDEN ON SMALLER DISPLAYS)
    - size: small
      widgets:
        - $include: left-column.yml
        
    # MAIN DISPLAY (ALWAYS DISPLAYED BUT GET RESIZED DEPENDING ON DISPLAY SIZE)
    - size: full
      widgets:
        - type: group
          widgets:
            - $include: main-bookmarks.yml
            #EPIC GAMES FREE GAMES
            - $include: epicstore-widget.yml
            - $include: other-bookmarks.yml

        - type: split-column
          widgets:
            #SERVER MONITORING
            - $include: beszel-widget1.yml
            # - $include: beszel-widget2.yml
            - type: server-stats
              servers:
                - type: local
                  name: Optinos

        - type: split-column
          widgets:
            # SERVICES/DOCKER CONTAINERS MONITORING
            - $include: services-monitoring.yml
            - $include: docker-monitoring.yml
                
            # QBITTORRENT STATS
            - $include: qbittorrent-widget.yml
            
            # MY MEMOS API
            # - type: custom-api
            #   title: My Memos
            #   title-url: ${HS_MEMOS_URL}
            #   cache: 10s
            #   url: ${HS_MEMOS_URL}/api/v1/memos
            #   template: |
            #     {{ if eq .Response.StatusCode 200 }}
            #       {{ $arr := .JSON.Array "memos" }}

            #       {{ if gt ( len $arr ) 0 }}
            #         <ul class="dynamic-columns list-gap-20 list-with-separator">
            #           {{ range $arr }}
            #             {{ $content := .String "content" }}
            #             <div class="flex gap-15 color-paragraph" style="white-space: pre-wrap;">
            #               {{ $content }}
            #             </div>
            #           {{ end }}
            #         </ul>

            #       {{ else }}
            #         <p class="color-highlight"> No Memos found. </p>
            #       {{ end }}

            #     {{ else }}
            #       <p class='color-negative'>Failed to retrieve memos: {{ .JSON.String "error.message" }} ({{ $.Response.Status }}) </p>
            #     {{ end }}
            # - type: iframe
            #   source: https://memos.optinos.duckdns.org/explore
            #   height: 500

            # ANCHOR API
            # - type: custom-api
            #   title: ${HS_ANCHOR_NAME}
            #   title-url: ${HS_ANCHOR_URL}
            #   cache: 10s
            #   url: ${HS_ANCHOR_URL}/api/notes
            #   method: GET
            #   headers:
            #     Authorization: "Bearer ea2806b47e6d86fc4b1fa79051000fb0c151375083f240e3d4ab72b81bd8e8ec"
            #     Content-Type: "application/json"
            #   template: |
            #     {{ if eq .Response.StatusCode 200 }}
            #       {{ $arr := . }}

            #       <p>{{ $arr }}</p>

            #     {{ else }}
            #       <p class='color-negative'>Failed to retrieve notes: {{ .JSON.String "error.message" }} ({{ $.Response.Status }}) </p>
            #     {{ end }}
            - type: iframe
              title: Anchor Notes
              title-url: ${HS_ANCHOR_URL}
              source: ${HS_ANCHOR_URL}
              height: 500
