services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - "8000:8000"
    environment:
      APPRISE_STATEFUL_MODE: simple
      APPRISE_WORKER_COUNT: 1
      APPRISE_ADMIN: "y"
      APPRISE_BASE_URL: "https://apprise.example.org"
    volumes:
      - ./config:/config
      - ./attach:/attach
    restart: unless-stopped

networks:
  default:
    external: true
    name: npm
