services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Indian/Mauritius
    group_add:
      - '993'
    volumes:
      - /home/nos/shared/docker/jellyfin/config:/config
      - /home/nos/shared/media/shows:/data/shows
      - /home/nos/shared/media/movies:/data/movies
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - 8096:8096
    #   - 8920:8920 #optional
    #   - 7359:7359/udp #optional
    #   - 1900:1900/udp #optional
    restart: unless-stopped

networks:
  default:
    external: true
    name: npm
