services:
  # gluetun:
  #   image: qmcgaw/gluetun
  #   container_name: gluetun
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 8080:8080       #qbittorrent webUI
  #     - 6881:6881       #qbittorrent
  #     - 6881:6881/udp   #qbittorrent
  #   environment:
  #     - VPN_SERVICE_PROVIDER=protonvpn
  #     - VPN_TYPE=wireguard
  #     - WIREGUARD_PRIVATE_KEY=key
  #     - SERVER_COUNTRIES=Netherlands
  #     - FREE_ONLY=on
  #   restart: unless-stopped


  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:libtorrentv1
    container_name: qbittorrent
    ports:
      - 8080:8080       #qbittorrent webUI
      - 6881:6881       #qbittorrent
      - 6881:6881/udp   #qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Indian/Mauritius
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config:/config
      - /home/nos/shared-storage/downloaded:/downloads
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 5G        # Hard limit: Container will be killed if it crosses this
        reservations:
          memory: 1G        # Soft limit: The minimum RAM allocated to start
    stop_grace_period: "10s" #optional
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Indian/Mauritius
    volumes:
      - /home/nos/shared-storage/docker/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
