services:
  uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: uptimekuma
    restart: unless-stopped
    # No need to expose ports if NPM is creating a domain name for it
    # ports:
    #   - 3001:3001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - uptime-kuma-data:/app/data

volumes:
  uptime-kuma-data:

networks:
  default:
    external: true
    name: npm
